@startuml
left to right direction
class Biblioteca{
    -Recursos : list
    +buscar_recurso()
    +prestar_recurso()
}


abstract Recursos{
    -Titulo : string
    -Autor : string
    -Prestado : bool
    
}




Recursos <|--- Libros
Recursos <|--- DVDs
Recursos <|--- Revistas
Recursos <|--- Peridicos
Recursos <|--- CDs

Biblioteca o-- Recursos


@endeuml